// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: network_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ESSIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESSIDRequest) Reset() {
	*x = ESSIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESSIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESSIDRequest) ProtoMessage() {}

func (x *ESSIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESSIDRequest.ProtoReflect.Descriptor instead.
func (*ESSIDRequest) Descriptor() ([]byte, []int) {
	return file_network_message_proto_rawDescGZIP(), []int{0}
}

type ESSIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ESSIDResponse) Reset() {
	*x = ESSIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESSIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESSIDResponse) ProtoMessage() {}

func (x *ESSIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESSIDResponse.ProtoReflect.Descriptor instead.
func (*ESSIDResponse) Descriptor() ([]byte, []int) {
	return file_network_message_proto_rawDescGZIP(), []int{1}
}

func (x *ESSIDResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IPAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IPAddressRequest) Reset() {
	*x = IPAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressRequest) ProtoMessage() {}

func (x *IPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressRequest.ProtoReflect.Descriptor instead.
func (*IPAddressRequest) Descriptor() ([]byte, []int) {
	return file_network_message_proto_rawDescGZIP(), []int{2}
}

type IPAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *IPAddressResponse) Reset() {
	*x = IPAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddressResponse) ProtoMessage() {}

func (x *IPAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddressResponse.ProtoReflect.Descriptor instead.
func (*IPAddressResponse) Descriptor() ([]byte, []int) {
	return file_network_message_proto_rawDescGZIP(), []int{3}
}

func (x *IPAddressResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_network_message_proto protoreflect.FileDescriptor

var file_network_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x69, 0x6e, 0x22, 0x0e, 0x0a, 0x0c,
	0x45, 0x53, 0x53, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0d,
	0x45, 0x53, 0x53, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x11, 0x49, 0x50, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_network_message_proto_rawDescOnce sync.Once
	file_network_message_proto_rawDescData = file_network_message_proto_rawDesc
)

func file_network_message_proto_rawDescGZIP() []byte {
	file_network_message_proto_rawDescOnce.Do(func() {
		file_network_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_message_proto_rawDescData)
	})
	return file_network_message_proto_rawDescData
}

var file_network_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_network_message_proto_goTypes = []interface{}{
	(*ESSIDRequest)(nil),      // 0: tin.ESSIDRequest
	(*ESSIDResponse)(nil),     // 1: tin.ESSIDResponse
	(*IPAddressRequest)(nil),  // 2: tin.IPAddressRequest
	(*IPAddressResponse)(nil), // 3: tin.IPAddressResponse
}
var file_network_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_message_proto_init() }
func file_network_message_proto_init() {
	if File_network_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_network_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESSIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESSIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_message_proto_goTypes,
		DependencyIndexes: file_network_message_proto_depIdxs,
		MessageInfos:      file_network_message_proto_msgTypes,
	}.Build()
	File_network_message_proto = out.File
	file_network_message_proto_rawDesc = nil
	file_network_message_proto_goTypes = nil
	file_network_message_proto_depIdxs = nil
}
